### ISSUE TITLE
Erasure namespace prefixs

### ISSUE THREAD

**Issue by Davorak** [supki/xml-html-conduit-lens#3]
I have been dealing with xml fragments with 'xml-html-conduit-lens` recently and ran into a problem where the namespace prefix was not being preserved when I thought it would be:

```
*Main> ("<xsl:if />" :: LT.Text) & xml %~ id
"<?xml version=\"1.0\" encoding=\"UTF-8\"?><if/>"
```

It does look like it is preserved in the parsing step:

```
*Main> ("<xsl:if />" :: LT.Text) ^? xml 
Just (Element {elementName = Name {nameLocalName = "if", nameNamespace = Nothing, namePrefix = Just "xsl"}, elementAttributes = fromList [], elementNodes = []})
```

This does not not match my intuition and it does not my admittedly vague understanding of lens `adjust` or `%~` acting much like fmap:

https://hackage.haskell.org/package/lens-1.2/docs/Control-Lens.html#v:adjust

I will take a look more closely later in the week.

edit: Aquick work around of course is just adding a prefix back

```
x & xml . prefix ?~ "xsl"
```

**Comment by Elvecent** [comment]
Is there at least a workaround for this? 😒
