### ISSUE TITLE
Help needed when using namespace

### ISSUE THREAD

**Issue by PierreR** [supki/xml-html-conduit-lens#4]
I am trying to use `xml-html-conduit-lens`with an input that use "namespaces" all along [such as this](https://paste.ee/p/JSdbm).

Unfortunately unless I remove the namespaces (the first `envelop` tag and all associated namespace), many traversal such as `node` seems to always return `[]`.

For instance:

Without namespace I can quickly figure out how to traverse the document:
```
> doc ^.. xml.name
["VirtualSystemCollection"]
> doc ^.. xml.node "Name"
[Element {elementName = Name {nameLocalName = "Name", nameNamespace = Nothing, namePrefix = Nothing}, elementAttributes = fromList [], elementNodes = [NodeContent "vApp_cicd"]}]
```
But without namespace :
```
> doc ^.. xml...name
["VirtualSystemCollection"]
> doc ^.. xml...node "Name"
[]
> doc ^.. xml...attributed (ix "id".only "vApp_cicd").node "Info"
[]
> doc ^.. xml...attributed (ix "id".only "vApp_cicd").elementNodes.traverse._NodeElement
[Element {elementName = Name {nameLocalName = "Info", nameNamespace = Just "http://schemas.dmtf.org/ovf/envelope/1", namePrefix = Just "ovf"}, elementAttributes =
 ....]
> λ> doc ^.. xml...attributed (ix "id".only "vApp_cicd").elementNodes.traverse._NodeElement.named (only "Info"))
[]
```

Could you help me to understand what's going on and provide some more examples with "namespaces" ?

Thanks a lot

**Comment by supki** [comment]
I should say that I have a (very) limited experience with XML namespaces.

Anyway, when working with namespaces, you have to qualify the local name part (e.g. "Name") with the namespace URI part (e.g. "http://schemas.dmtf.org/ovf/envelope/1"). The easiest way to do that with `xml-conduit` is to use the [Clark notation](http://www.jclark.com/xml/xmlns.htm):

```
>>> :set -XOverloadedStrings
>>> doc ^.. xml...node "{http://schemas.dmtf.org/ovf/envelope/1}Name"
Just (Element {elementName = Name {nameLocalName = "Name", nameNamespace = Just "http://schemas.dmtf.org/ovf/envelope/1", namePrefix = Just "ovf"}, elementAttributes = fromList [], elementNodes = [NodeContent "vApp_cicd"]})
>>> doc ^.. xml...attributed (ix "{http://schemas.dmtf.org/ovf/envelope/1}id".only "vApp_cicd").node "{http://schemas.dmtf.org/ovf/envelope/1}Info"
[Element {elementName = Name {nameLocalName = "Info", nameNamespace = Just "http://schemas.dmtf.org/ovf/envelope/1", namePrefix = Just "ovf"}, elementAttributes = fromList [], elementNodes = [NodeContent "A collection of virtual machines"]}]
```

Hope this helps.

**Comment by PierreR** [comment]
It works !

I wouldn't find this on my own. Thanks for your quick help !
